name: rmlint Alpine build
on:
  workflow_dispatch:
jobs:
  package_and_update:
    permissions: write-all
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
      options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install build dependencies
        run: |
          echo "http://dl-cdn.alpinelinux.org/alpine/v3.22/main" > /etc/apk/repositories
          echo "http://dl-cdn.alpinelinux.org/alpine/v3.22/community" >> /etc/apk/repositories
          apk update

          apk add --no-cache git scons pkgconf gettext build-base jq curl wget bash

      - name: Install optional dependencies for more features
        run: |
          apk add --no-cache elfutils-dev glib-dev util-linux-dev json-glib-dev

      - name: Install optional dependencies for building documentation
        run: |
          apk add --no-cache python3 py3-sphinx 
          # py3-sphinx-bootstrap-theme

      - name: Install optional dependencies for the GUI
        run: |
          apk add --no-cache py3-setuptools py3-cairo py3-gobject3 gtk+3.0 polkit librsvg py3-colorlog

      - name: Install optional dependencies for tests
        run: |
          apk add --no-cache py3-pytest py3-psutil
          apk add --no-cache py3-pip python3-dev build-base
          pip install --break-system-packages sphinx-bootstrap-theme pyxattr
      - name: Build
        run: |
          #!/bin/sh
          apk add --no-cache abuild sudo scons git pkgconf gettext fakeroot curl jq
          
          adduser -D builder
          adduser builder abuild
          
          mkdir -p /home/builder/src /home/builder/.abuild
          chown -R builder:builder /home/builder
          
          # Generate abuild key
          sudo abuild-keygen -a -i -n
          mv /root/.abuild/* /home/builder/.abuild/
          chown -R builder:builder /home/builder/.abuild
          
          # Fetch latest rmlint release
          tag=$(curl -s https://api.github.com/repos/sahib/rmlint/releases/latest | jq -r .tag_name)
          version="${tag#v}"
          echo "TAG=$tag"
          
          # Create source directory and download tarball
          mkdir -p /home/builder/src/rmlint/src
          curl -L -o /home/builder/src/rmlint/src/rmlint-$version.tar.gz "https://github.com/sahib/rmlint/archive/refs/tags/v$version.tar.gz"
          chown -R builder:builder /home/builder/src/rmlint
          
          # Create APKBUILD pointing to local tarball (without checksum yet)
          cat > /home/builder/src/rmlint/APKBUILD <<EOF
          pkgname=rmlint
          pkgver=$version
          pkgrel=0
          pkgdesc="rmlint compiled from source with GUI"
          url="https://github.com/sahib/rmlint"
          arch="x86_64"
          license="GPL-3.0-or-later"
          depends="gtk+3.0 py3-gobject3 py3-cairo"
          makedepends="scons git pkgconf gettext"
          source="https://github.com/sahib/rmlint/archive/refs/tags/v${pkgver}.tar.gz"
            builddir="$srcdir/$pkgname-$pkgver"
          
          build() {
              cd "$builddir"
              scons config
          }
          
          package() {
              cd "$builddir"
              scons --prefix="$pkgdir/usr/local" install
          }
          EOF
          
          # Configure abuild to use builder key
          builder_key=$(ls /home/builder/.abuild/*.rsa | head -n1)
          echo "PACKAGER_PRIVKEY=\"$builder_key\"" >> /home/builder/.abuild/abuild.conf
          chown builder:builder /home/builder/.abuild/abuild.conf
          chmod 600 /home/builder/.abuild/abuild.conf
          
          # Generate checksum for the tarball
          sudo -u builder bash -c "cd /home/builder/src/rmlint && abuild checksum"
          
          # Build the APK
          sudo -u builder bash -c "cd /home/builder/src/rmlint && abuild -r -F"
          
          # Locate the resulting APK
          apk_file=$(find /home/builder/packages/ -name "*.apk" | head -n1)
          echo "APK_FILE=$apk_file"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.TAG }}
          make_latest: true
          files: ${{ env.APK_FILE }}
