name: rmlint push to Docker
on:
  workflow_dispatch:
jobs:
  package_and_update:
    permissions: write-all
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
      options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: bobbintb/docker-rmlint-unraid:latest
