name: rmlint Ubuntu build
on:
  workflow_dispatch:
jobs:
  package_and_update:
    permissions: write-all
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
      options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update apt
        run: |
          apt update
          # Ubuntu-only:
          apt install -y software-properties-common && add-apt-repository universe
          apt install -y git scons pkgconf gettext build-essential
          # Optional dependencies for more features:
          apt install -y libelf-dev libglib2.0-dev libblkid-dev libjson-glib-1.0-0 libjson-glib-dev jq
          # Optional dependencies for building documentation:
          apt install -y python3-sphinx python3-sphinx-bootstrap-theme
          # Optional dependencies for the GUI:
          apt install -y python3-setuptools python3-gi-cairo gir1.2-gtksource-4 gir1.2-polkit-1.0 gir1.2-rsvg-2.0 python3-colorlog
          # Optional dependancies for tests:
          apt install -y python3-pytest python3-psutil python3-xattr
          tag=$(curl -s https://api.github.com/repos/sahib/rmlint/releases/latest | jq -r .tag_name)
          git clone --branch $tag --depth 1 https://github.com/sahib/rmlint.git
          cd rmlint/
          scons config
          
      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     tag_name: v${{ env.VERSION }}
      #     make_latest: true
      #     files: |
      #       *.deb
