name: rmlint Ubuntu build
on:
  workflow_dispatch:
jobs:
  package_and_update:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update apt
        run: |
          sudo apt update
          # Ubuntu-only:
          sudo apt install software-properties-common && add-apt-repository universe
          sudo apt install git scons pkgconf gettext build-essential
          # Optional dependencies for more features:
          sudo apt install libelf-dev libglib2.0-dev libblkid-dev libjson-glib-1.0-0 libjson-glib-dev
          # Optional dependencies for building documentation:
          $ sudo apt install python3-sphinx python3-sphinx-bootstrap-theme
          # Optional dependencies for the GUI:
          $ sudo apt install python3-setuptools python3-gi-cairo gir1.2-gtksource-4 gir1.2-polkit-1.0 gir1.2-rsvg-2.0 python3-colorlog
          # Optional dependancies for tests:
          $ sudo apt install python3-pytest python3-psutil python3-xattr
          
      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     tag_name: v${{ env.VERSION }}
      #     make_latest: true
      #     files: |
      #       *.deb
